name: Discord Webhook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Novo commit ou Pull Request para o repositório!"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
